### ISSUE TITLE
Problems with `matrix_bufAlloc()` in `matrix` library

### ISSUE THREAD

**Issue by PNieck** [phoenix-pilot/phoenix-pilot-core#33]
# 1) Negative number of rows and columns
### EDIT: bug was repaired ✅️

It is possible to create matrix with negative number of rows and columns.

Such a invocation:
```c
matrix_bufAlloc( &A, -10, -5);
```
returns $0$.

This leads to incorrect values of `A.rows` and `A.columns`. Number of columns and number of rows have to be negative at the same time.

# 2) Potential problems with passing a pointer

In my opinion it can not be clear enough for potential user, what pointer, which is passed to the `phx_newmatrix()` needs to points to already existing matrix. This can lead to such errors:
```c
matrix_t *A;
matrix_bufAlloc(A, 5, 10);
```
or
```c
matrix_t *A = NULL;
matrix_bufAlloc(A, 5, 10);
```
This must be described in docs. I would prefer to rewrite function so that it returns a pointer to the matrix:
```c
matrix_t *A = matrix_bufAlloc(5, 10);
```

# 3) Function is not resistant to overflow while calculating number of elements
### EDIT: bug was repaired ✅️

For example it is possible to create such a matrix:
```c
matrix_bufAlloc(&A, INT_MAX, INT_MAX);
```

**Comment by niewim19** [comment]
# @ 2) Potential problems with passing a pointer
Function is specified as:
``` c
int phx_newmatrix(phmatrix_t *matrix, int rows, int cols);
```
If this function should dynamically allocate space for `phatrix_t` structure, then there should be a way of retrieving pointer value to newly allocated memory. And ther is none. This indicates that it should accept _pointer to already allocated (dynamically or not) `phmatrix_t` structure_. It indeed needs a commentary in header file for clarification, but not changes in the function itself.

However a catch for `NULL` value should be imposed and `-1` should be returned.

**Comment by niewim19** [comment]
After name change from `newmatrix` to `'bufAlloc` it is indicated that this function needs and preexisting `matrix_t` structure to work properly. By this problem @2 is mitigated.

**Closing this issue** as both other subissues are solved. Thank you for finding those problems ans solving them!
